global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'trainbooking-services'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'auth-service:3001'
        - 'user-service:3002'
        - 'train-service:3003'
        - 'booking-service:3004'
        - 'admin-service:3005'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
