---
- name: Deploy Microservices
  hosts: all
  tasks:
    - name: Create K8s Namespace
      command: kubectl create namespace trainbooking
      ignore_errors: yes

    - name: Apply Kubernetes Manifests
      command: kubectl apply -f "{{ playbook_dir }}/../k8s/"
      ignore_errors: yes
